name: Terraform Apply or Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose the Terraform action'
        required: true
        default: 'apply'  # Default action is apply
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform-apply-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::302263075199:role/OIDC-Terraform
          aws-region: us-west-2

      - name: List Directory Contents
        run: ls -la ./Infra

      - name: Terraform Init
        run: terraform init
        working-directory: ./Infra

      - name: Perform Action
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -var-file=terraform.tfvars -auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action selected."
            exit 1
        working-directory: ./Infra
